on: [push, pull_request]
name: Run CI
jobs:
  make:
    name: Build and Upload Sileo
    runs-on: macos-latest
    env:
      THEOS: theos
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Install ldid and dpkg
        run: |
          brew install ldid dpkg
      - name: Restore CocoaPods cache
        uses: actions/cache@v2
        id: cache
        with:
          path: Pods
          key: pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            pods-
      - name: Install Pods
        if: steps.cache.outputs.cache-hit != 'true'
        run: pod install
      - name: Build Sileo
        id: build
        run: |
         make clean package BETA=1 DEBUG=0
         echo "::set-output name=package::$(ls -t packages | head -n1)"
      - name: Upload To Repo
        env: # 
          token: ${{ secrets.UPLOAD_KEY }}
        run: |
          curl -F deb=@./packages/${{ steps.build_package.outputs.package }} -H "Auth: ${token}" -H "Path: BetaRepo/Packages/Sileo" -H "Build: ${GITHUB_SHA::6}" https://api.anamy.gay/private/repo/upload
  lint:
    name: Lint Sileo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
