on:
  push:
    branches:
      - 2.1.x
name: Build
jobs:
  make:
    name: Build and Upload Sileo
    runs-on: macos-latest
    steps:
      - uses: actions/cache@v2
        id: procache
        with:
          path: ~/__cache
          key: ${{ runner.os }}-pro
          
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
        
      - name: Setup Procursus Bootstrap (install)
        if: steps.procache.outputs.cache-hit != 'true'
        run: |
          wget https://apt.procurs.us/bootstrap_darwin-amd64.tar.zst
          sudo gtar --preserve-permissions -xkf ./bootstrap_darwin-amd64.tar.zst -C /
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
          PATH=/opt/procursus/sbin:/opt/procursus/bin:$PATH sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V dist-upgrade -y || :
          sudo /opt/procursus/bin/apt -V dist-upgrade -y
          sudo /opt/procursus/bin/apt install ldid -y
      - name: Add Procursus to PATH
        run: |
          echo '/opt/procursus/sbin:/opt/procursus/bin' >> $GITHUB_PATH
      - name: Setup Procursus Bootstrap (cache)
        if: steps.procache.outputs.cache-hit == 'true'
        run: |
          sudo rsync -a ~/__cache/procursus /opt
          sudo /opt/procursus/bin/apt update
          sudo /opt/procursus/bin/apt -V dist-upgrade -y
      - name: Build Sileo Nightly
        run: |
          make clean package NIGHTLY=1 DEBUG=0
      - name: Upload To Repo
        env: # 
           token: ${{ secrets.AMY_REPO_SECRET }}
        run: |
           package=$(ls -t packages | head -1)
           curl -F deb="@./packages/${package}" -H "Auth: ${token}" https://api.anamy.gay/private/repo/sileo
      - name: Copy Procursus to Cache Location
        run: |
          sudo mkdir -p ~/__cache
          sudo rsync -a /opt/procursus __cache
  lint:
    name: Lint Sileo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_12.4.app 
      - name: Run Tests
        run: xcodebuild test -scheme "Sileo Demo" -project Sileo.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4' | xcpretty && exit ${PIPESTATUS[0]}
